Manworld/urls.py
from django.contrib import admin
from django.urls import path, include
from posts.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('posts/', include('posts.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import index, history, chart, location, notice, news, reservation, about, business, service, create


app_name = "posts"
urlpatterns = [
    path('index/', index, name="index"),
    path('history/', history, name="history"),
    path('chart/', chart, name="chart"),
    path('location/', location, name="location"),
    path('business/', business, name="business"),
    path('service/', service, name="service"),
    path('notice/', notice, name="notice"),
    path('news/', news, name="news"),
    path('reservation/', reservation, name="reservation"),
    path('about/', about, name="about"),
    path('create/', create, name="create"),
]

posts/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    class Meta:
        verbose_name = "공지사항"
        ordering = ['-created_at']

    title = models.CharField(max_length=200, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    user = models.CharField(max_length=100, verbose_name="작성자")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="등록시간")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="업데이트시간")
    image = models.ImageField(upload_to="posts/img", blank=True, default="posts/default/1.jpg", verbose_name="썸네일 이미지")

    def __unicode__(self):
        return self.title


class Counsel(models.Model):
    class Meta:
        verbose_name = "상담"
        ordering = ['-created_at']

    name = models.CharField(max_length=200, verbose_name="이름")
    phone = models.CharField(max_length=200, verbose_name="연락처")
    title = models.CharField(max_length=200, verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    password = models.CharField(max_length=200, verbose_name="비밀번호")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="등록시간")

    def __unicode__(self):
        return self.title

posts/forms.py
from django import forms
from .models import Post, Counsel
from django_summernote.widgets import SummernoteWidget


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'user', 'image']
        labels = {
            'title': '제목',
            'content': '내용',
            'user': '작성자',
            'image': '썸네일 이미지',
        }
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'content': SummernoteWidget(),
        }


class CounselForm(forms.ModelForm):
    class Meta:
        model = Counsel
        fields = ['name', 'phone', 'title', 'content', 'password']
        labels = {
            'title': '제목',
            'content': '내용',
            'phone': '연락처',
            'name': '이름',
            'password': '비밀번호',

        }

        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control'

            }),
            'content': forms.Textarea(attrs={
                'class': 'form-control'
            }),
        }

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from .forms import PostForm, CounselForm
from django.views.decorators.http import require_POST


def index(request):
    return render(request, 'posts/index.html')


def history(request):
    return render(request, 'posts/history.html')


def chart(request):
    return render(request, 'posts/chart.html')


def location(request):
    return render(request, 'posts/location.html')


def notice(request):
    return render(request, 'posts/notice.html')


def reservation(request):
    return render(request, 'posts/reservation.html')


def about(request):
    return render(request, 'posts/about.html')


def service(request):
    return render(request, 'posts/service.html')


def business(request):
    return render(request, 'posts/business.html')


def news(request):
    context = {
        'posts': Post.objects.order_by('-created_at')
    }
    return render(request, 'posts/news.html', context)


@require_POST
def create(request):
    form = CounselForm(request.POST)
    if form.is_valid():
        form.save()
    return render(request, 'posts/reservation.html')

posts/templates/posts/about.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>about</title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_detail.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700;800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;500;700&display=swap" rel="stylesheet">

    <style type="text/css">
      .main_img{
        background: url("{% static 'img/2.jpg' %}") no-repeat center center;
      }
    </style>
</head>
<body>
  <div id="body">
    <div id="content">
      <a href="#" class="openmenu" onclick='openNav()'><img src="{% static 'img/square_24.png' %}" alt=""></a>
      <div class="logo">
        <a href="{% url 'posts:index' %}"><img id="logo" src="{% static 'img/logo_150.png' %}" alt=""></a>
        <p>White & Blue Brokerage Company L.L.C</p>
      </div>

      <!-- navbar -->
      <div id="mysidenav" class="nav">
        <a href="#" class="closebtn" onclick='closeNav()'>x</a>
        <div class="menu">
        <ul>
            <h1>회사 소개</h1>
            <li><a href="{% url 'posts:about' %}">About Us</a></li>
            <li><a href="{% url 'posts:history' %}">회사 연혁</a></li>
            <li><a href="{% url 'posts:chart' %}">조직도</a></li>
            <li><a href="{% url 'posts:location' %}">오시는 길</a></li>
        </ul>
        <ul>
            <h1>서비스</h1>
            <li><a href="{% url 'posts:service' %}">현지 법인/지사 설립 컨설팅</a></li>
            <li><a href="{% url 'posts:service' %}">시장 진출 전략 수립</a></li>
            <li><a href="{% url 'posts:service' %}">밴더 등록 컨설팅</a></li>
            <li><a href="{% url 'posts:service' %}">투자환경 조사 대행(법률, 회계, 노무)</a></li>
            <li><a href="{% url 'posts:service' %}">무역플랫폼(중동, 아프리카 국가 대상)</a></li>
            <li><a href="{% url 'posts:service' %}">공연 및 행사기획</a></li>
        </ul>
        <ul>
            <h1>비즈니스 제휴</h1>
            <li><a href="{% url 'posts:business' %}">관급 입찰 정보 제공</a></li>
            <li><a href="{% url 'posts:business' %}">관급 입찰 JV 컨설팅</a></li>
        </ul>
        <ul>
            <h1>공지 및 정보</h1>
            <li><a href="{% url 'posts:notice' %}">공지사항</a></li>
            <li><a href="{% url 'posts:news' %}">UAE 뉴스</a></li>
        </ul>
        <ul>
            <h1>전문 상담 예약</h1>
            <li><a href="{% url 'posts:reservation' %}">일정표 상 예약 가능 여부 확인</a></li>
        </ul>
        </div>
      </div>


      <div class="main_img"></div>
  
      <div class="page">
        <h1>White & Blue Brokerage Company L.L.C</h1>
        <p>White & Blue는 Abu-Dhabi 진출을 희망하는 한국 및 외국 기업들에게 현지 정보 제공 및 경영지원, 시장조사 등의 업무를 수행하는 종합 컨설팅 회사이며, 법인 설립부터 운영지원까지 Abu-Dhabi 진출기업과 비지니스의 성공을 함께 합니다. <br>
          매력적인 Abu-Dhabi 시장의 진입 장벽은 언어 소통 및 복잡하고 불합리한 행정 처리, 노동 허가 및 거주증 발급의 어려움 등 다양합니다. <br>
          또한 낯선 환경에서 시간과 비용을 낭비하지 않고 원하는 사업에 집중할 수 있도록 각 분야별 풍부한 경험과 탁월한 전문지식을 바탕으로 Abu-Dhabi에 진출하고자하는 기업에 Abu-Dhabi 내 사업 환경의 이해를 도와 드릴뿐 아니라 성공적인 Abu-Dhabi 사업운영을 위한 원스톱 서비스를 지원해 드리는 고객과 함께 고민하고 성장하는 성공의 동반자 White & Blue입니다.</p>
      </div>
    </div>
  </div>

  <!-- footer -->
  <div class="footer">
    <div class="inner">
      <h2>White & Blue Brockerage Company L.L.C</h2>
      <div>
        <ul>
          <li>
            <strong>대표자</strong>
            <span>Hussain Abdul Rahim Abdulla Hussain Alkhoori / 이 정 필</span>
          </li>
          <li>
            <strong>주소</strong>
            <span>[한국] 서울특별시 종로구 사직로 130 (적선현대빌딩 1105호)</span>
          </li>
          <li>
            <strong>연락처</strong>
            <span>[KOR]Tel.+82-2-786-1976 Fax.+82-2-786-1978</span>
            <span>[UAE]Tel.+   Fax.</span>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <script>
    function openNav() {
      document.getElementById('mysidenav').style.width = '100%';
    }
    function closeNav() {
      document.getElementById('mysidenav').style.width = '0';
    }
  </script>
</body>
</html>

posts/templates/posts/business.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/service.css' %}">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
  <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700;800&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;500;700&display=swap" rel="stylesheet">
  <title>Business</title>

  <style>
    .image{
        background: url("{% static 'img/header/landscape-4098802_1920.jpg' %}") no-repeat center center;
    }
    .btn-group button{
        width: 700px;
    }
    .btn-group{
        margin: 30px auto;
        width: 1400px;
    }
    @media (max-width: 1024px) {
        .btn-group {
            width: 800px;
        }

        .btn-group button {
            width: 400px;
            height: 50px;
            float: left;
        }
    }
    @media (max-width: 800px){
        .btn-group{
            width: 100%;
            display: flex;
            flex-wrap: wrap;
        }
        .btn-group button:not(:last-child) {
            border-right: 1px solid #000;;
        }
        .btn-group button{
            width: 200px;
            height: 50px;
            float: left;
        }
    }

  </style>
</head>
<body>

    <div id="body">
        <div id="content">
            <a href="#" class="openmenu" onclick='openNav()'><img src="{% static 'img/square_24.png' %}" alt=""></a>
        <div class="logo">
            <a href="{% url 'posts:index' %}"><img id="logo" src="{% static 'img/logo_150.png' %}" alt=""></a>
            <p>White & Blue Brokerage Company L.L.C</p>
        </div>

        <!-- navbar -->
        <div id="mysidenav" class="nav">
            <a href="#" class="closebtn" onclick='closeNav()'>x</a>
            <div class="menu">
            <ul>
                <h1>회사 소개</h1>
                <li><a href="{% url 'posts:about' %}">About Us</a></li>
                <li><a href="{% url 'posts:history' %}">회사 연혁</a></li>
                <li><a href="{% url 'posts:chart' %}">조직도</a></li>
                <li><a href="{% url 'posts:location' %}">오시는 길</a></li>
            </ul>
            <ul>
            <h1>서비스</h1>
                <li><a href="{% url 'posts:service' %}">현지 법인/지사 설립 컨설팅</a></li>
                <li><a href="{% url 'posts:service' %}">시장 진출 전략 수립</a></li>
                <li><a href="{% url 'posts:service' %}">밴더 등록 컨설팅</a></li>
                <li><a href="{% url 'posts:service' %}">투자환경 조사 대행(법률, 회계, 노무)</a></li>
                <li><a href="{% url 'posts:service' %}">무역플랫폼(중동, 아프리카 국가 대상)</a></li>
                <li><a href="{% url 'posts:service' %}">공연 및 행사기획</a></li>
            </ul>
            <ul>
                <h1>비즈니스 제휴</h1>
                <li><a href="{% url 'posts:business' %}">관급 입찰 정보 제공</a></li>
                <li><a href="{% url 'posts:business' %}">관급 입찰 JV 컨설팅</a></li>
            </ul>
            <ul>
                <h1>공지 및 정보</h1>
                <li><a href="{% url 'posts:notice' %}">공지사항</a></li>
                <li><a href="{% url 'posts:news' %}">UAE 뉴스</a></li>
            </ul>
            <ul>
                <h1>전문 상담 예약</h1>
                <li><a href="{% url 'posts:reservation' %}">일정표 상 예약 가능 여부 확인</a></li>
            </ul>
            </div>
        </div>

        <!-- 상단 이미지 -->
        <div class="image">
            <div class="cover"></div>
            <h1>비즈니스 제휴</h1>
        </div>

        <!-- button -->
        <div class="btn-group">
            <button onclick='showPage1()'>관급 입찰 정보 제공</button>
            <button onclick='showPage2()'>관급 입찰 JV 컨설팅</button>
        </div>

        <!-- button 해당 page -->
        <div class="page" id="a">
            <div class="page_content">
                <h1>관급 입찰 정보 제공</h1>
                <p>현지 입찰 정보를 고객사에 맞는 <span id="highlight">“맞춤형 입찰정보 서비스”</span> 제공</p>
            </div>
        </div>

        <div class="page" id="b">
            <div class="page_content">
                <h1>관급 입찰 JV 컨설팅</h1>
                <p>입찰 참여에 관심이 있으나 단독적인 입찰에 부담을
                <br>줄일 수 있도록 <span id="highlight">파트너 회사 연결</span></p>
            </div>
        </div>
        </div>

    </div>

    <!-- footer -->
    <footer class="footer">
        <div class="inner">
        <h2>White & Blue Brockerage Company L.L.C</h2>
        <div>
            <ul>
            <li>
                <strong>대표자</strong>
                <span>Hussain Abdul Rahim Abdulla Hussain Alkhoori | 이 정 필</span>
            </li>
            <li>
                <strong>주소</strong>
                <span>[한국] 서울특별시 종로구 사직로 130 (적선현대빌딩 1105호)</span>
            </li>
            <li>
                <strong>연락처</strong>
                <span>[KOR]Tel.+82-2-786-1976 Fax.+82-2-786-1978</span>
                <span>[UAE]Tel.+   Fax.</span>
            </li>
            </ul>
        </div>
        </div>
    </footer>

    <script>
        function openNav() {
            document.getElementById('mysidenav').style.width = '100%';
        }
        function closeNav() {
            document.getElementById('mysidenav').style.width = '0';
        }

        let a = document.getElementById("a");
        let b = document.getElementById("b");
        let c = document.getElementById("c");
        let d = document.getElementById("d");

        function showPage1(){
            a.style.display = 'block';
            b.style.display = 'none';
            c.style.display = 'none';
            d.style.display = 'none';
        }
        function showPage2() {
            a.style.display = 'none';
            b.style.display = 'block';
            d.style.display = 'none';
            c.style.display = 'none';
        }
        
        function showBtn(){
            let show = document.getElementById("btn");

            if(show.style.display == 'none'){
                show.style.display = 'block';
            }else{
                show.style.display = 'none';
            }
        }
  </script>
</body>
</html>

posts/templates/posts/chart.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_detail.css' %}">
    <link rel="stylesheet" href="{% static 'css/chart.css' %}">
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700;800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;500;700&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<div>
  <div id="body">
    <div id="content">
      <a href="#" class="openmenu" onclick='openNav()'><img src="{% static 'img/square_24.png' %}" alt=""></a>
      <div class="logo">
            <a href="{% url 'posts:index' %}"><img id="logo" src="{% static 'img/logo_150.png' %}" alt=""></a>
            <p>White & Blue Brokerage Company L.L.C</p>
        </div>

        <!-- navbar -->
        <div id="mysidenav" class="nav">
            <a href="#" class="closebtn" onclick='closeNav()'>x</a>
            <div class="menu">
            <ul>
                <h1>회사 소개</h1>
                <li><a href="{% url 'posts:about' %}">About Us</a></li>
                <li><a href="{% url 'posts:history' %}">회사 연혁</a></li>
                <li><a href="{% url 'posts:chart' %}">조직도</a></li>
                <li><a href="{% url 'posts:location' %}">오시는 길</a></li>
            </ul>
            <ul>
                <h1>서비스</h1>
                <li><a href="{% url 'posts:service' %}">현지 법인/지사 설립 컨설팅</a></li>
                <li><a href="{% url 'posts:service' %}">시장 진출 전략 수립</a></li>
                <li><a href="{% url 'posts:service' %}">밴더 등록 컨설팅</a></li>
                <li><a href="{% url 'posts:service' %}">투자환경 조사 대행(법률, 회계, 노무)</a></li>
                <li><a href="{% url 'posts:service' %}">무역플랫폼(중동, 아프리카 국가 대상)</a></li>
                <li><a href="{% url 'posts:service' %}">공연 및 행사기획</a></li>
            </ul>
            <ul>
                <h1>비즈니스 제휴</h1>
                <li><a href="{% url 'posts:business' %}">관급 입찰 정보 제공</a></li>
                <li><a href="{% url 'posts:business' %}">관급 입찰 JV 컨설팅</a></li>
            </ul>
            <ul>
                <h1>공지 및 정보</h1>
                <li><a href="{% url 'posts:notice' %}">공지사항</a></li>
                <li><a href="{% url 'posts:news' %}">UAE 뉴스</a></li>
            </ul>
            <ul>
                <h1>전문 상담 예약</h1>
                <li><a href="{% url 'posts:reservation' %}">일정표 상 예약 가능 여부 확인</a></li>
            </ul>
            </div>
        </div>

      <div class="wrapper">
        <!-- 상단 이미지 -->
        <div class="image">
          <div class="cover"></div>
          <h1>White & Blue Brokerage Company L.L.C</h1>
        </div>

          <img src="{% static 'img/캡처.jpg' %}" alt="">

        <!-- 조직도 -->
          <div class="chart">
              <h1><span id="highlight">ABU-DHABI HEADQUARTERS</span></h1>
              <div class="chart_img"></div>
          </div>

          <div class="chart">
              <h1>SEOUL LIAISON OFFICE</h1>
              <div class="chart_img"></div>
          </div>


          </div>
      </div>
    </div>
  </div>
</div>

  <!-- footer -->
  <div class="footer">
    <div class="inner">
      <h2>White & Blue Brockerage Company L.L.C</h2>
      <div>
        <ul>
          <li>
            <strong>대표자</strong>
            <span>Hussain Abdul Rahim Abdulla Hussain Alkhoori / 이 정 필</span>
          </li>
          <li>
            <strong>주소</strong>
            <span>[한국] 서울특별시 종로구 사직로 130 (적선현대빌딩 1105호)</span>
          </li>
          <li>
            <strong>연락처</strong>
            <span>[KOR]Tel.+82-2-786-1976 Fax.+82-2-786-1978</span>
            <span>[UAE]Tel.+   Fax.</span>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <script>
    function openNav() {
      document.getElementById('mysidenav').style.width = '100%';
    }
    function closeNav() {
      document.getElementById('mysidenav').style.width = '0';
    }
  </script>
</body>
</html>

posts/templates/posts/reservation.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/reservation.css' %}">
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700;800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;500;700&display=swap" rel="stylesheet">
    <title>Reservation</title>

    <style>
      .image{
        background: url("{% static 'img/header/table-2254656_1920.jpg' %}") no-repeat center center;
        background-size: cover;
      }
    </style>
</head>
<body>
<a href="#" class="openmenu" onclick='openNav()'><img src="{% static 'img/square_24.png' %}" alt=""></a>
  <div class="logo">
    <a href="{% url 'posts:index' %}"><img id="logo" src="{% static 'img/logo_150.png' %}" alt=""></a>
    <p>White & Blue Brokerage Company L.L.C</p>
  </div>

  <div>
    <div id="mysidenav" class="nav">
        <a href="#" class="closebtn" onclick='closeNav()'>x</a>
        <div class="menu">
          <ul>
              <h1>회사 소개</h1>
              <li><a href="{% url 'posts:about' %}">About Us</a></li>
              <li><a href="{% url 'posts:history' %}">회사 연혁</a></li>
              <li><a href="{% url 'posts:chart' %}">조직도</a></li>
              <li><a href="{% url 'posts:location' %}">오시는 길</a></li>
          </ul>
          <ul>
                <h1>서비스</h1>
                <li><a href="{% url 'posts:service' %}">현지 법인/지사 설립 컨설팅</a></li>
                <li><a href="{% url 'posts:service' %}">시장 진출 전략 수립</a></li>
                <li><a href="{% url 'posts:service' %}">밴더 등록 컨설팅</a></li>
                <li><a href="{% url 'posts:service' %}">투자환경 조사 대행(법률, 회계, 노무)</a></li>
                <li><a href="{% url 'posts:service' %}">무역플랫폼(중동, 아프리카 국가 대상)</a></li>
                <li><a href="{% url 'posts:service' %}">공연 및 행사기획</a></li>
          </ul>
          <ul>
              <h1>비즈니스 제휴</h1>
              <li><a href="{% url 'posts:business' %}">관급 입찰 정보 제공</a></li>
              <li><a href="{% url 'posts:business' %}">관급 입찰 JV 컨설팅</a></li>
          </ul>
          <ul>
              <h1>공지 및 정보</h1>
              <li><a href="{% url 'posts:notice' %}">공지사항</a></li>
              <li><a href="{% url 'posts:news' %}">UAE 뉴스</a></li>
          </ul>
          <ul>
              <h1>전문 상담 예약</h1>
              <li><a href="{% url 'posts:reservation' %}">일정표 상 예약 가능 여부 확인</a></li>
          </ul>
        </div>
      </div>

      <!-- 상단 이미지 -->
      <div class="image">
        <div class="cover"></div>
        <h1>상담 예약</h1>
      </div>

       <div class="counsel">
           <form action="{% url 'posts:create' %}" method="POST">
               {% csrf_token %}
                <div class="table-box">
                  <table>
                    <tr>
                      <th>이름</th>
                      <td><input type="text" name="name" id="name"></td>
                    </tr>
                    <tr>
                      <th>연락처</th>
                      <td><input type="text" name="phone" id="phone"></td>
                    </tr>
                    <tr>
                      <th>제목</th>
                      <td><input type="text" name="title" id="title"></td>
                    </tr>
                    <tr>
                      <th>내용</th>
                      <td><input type="text" name="content" id="content"></td>
                    </tr>
                    <tr>
                      <th>비밀번호</th>
                      <td><input type="password" name="password" id="password"></td>
                    </tr>
                  </table>
                </div>
                  <div class="btn">
                    <button type="submit" id="btn_finish">작성완료</button>
                    <button type="reset" id="btn_cancel">취소</button>
                  </div>
          </form>
      </div>
  </div>

  <div class="footer2">
    <div class="inner">
      <h2>White & Blue Brockerage Company L.L.C</h2>
      <div>
        <ul>
          <li>
            <strong>대표자</strong>
            <span>Hussain Abdul Rahim Abdulla Hussain Alkhoori / 이 정 필</span>
          </li>
          <li>
            <strong>주소</strong>
            <span>[한국] 서울특별시 종로구 사직로 130 (적선현대빌딩 1105호)</span>
          </li>
          <li>
            <strong>연락처</strong>
            <span>[KOR]Tel.+82-2-786-1976 Fax.+82-2-786-1978</span>
            <span>[UAE]Tel.+   Fax.</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <script>
    function openNav() {
      document.getElementById('mysidenav').style.width = '100%';
    }
    function closeNav() {
      document.getElementById('mysidenav').style.width = '0';
    }
  </script>
</body>
</html>